### ISSUE TITLE
print(data[i : i + 9]) causes a lot of lines in HA log file

### ISSUE THREAD

**Issue by WhistleMaster** [Bouni/python-luxtronik#11]
In Home Assistant, when using your custom component, a lot of lines appears in the log due to this `print` [here](https://github.com/Bouni/python-luxtronik/blob/36fc369ed0e885bfd8bb619f885cbc7ae26354c8/luxtronik/calculations.py#L273).

<img width="597" alt="Screenshot 2020-05-05 at 19 39 41" src="https://user-images.githubusercontent.com/1544568/81097566-64b03000-8f08-11ea-86a0-59c9000a18ad.png">
<img width="275" alt="Screenshot 2020-05-05 at 19 39 45" src="https://user-images.githubusercontent.com/1544568/81097568-6548c680-8f08-11ea-9b75-1edfcab854c9.png">

**Comment by Bouni** [comment]
Good catch @WhistleMaster !
I was looking for the source of that myself and wasn't able to locate where it was coming from 🙈 
Will fix that ASAP!

**Comment by Bouni** [comment]
Fixed!
