### ISSUE TITLE
Calculation ID 267: desired room temperature

### ISSUE THREAD

**Issue by RobinFlikkema** [Bouni/python-luxtronik#143]
I would like to open this issue, as I currently seem to have found Calculation 267. It would be great if others could confirm this.

`267 : 2147483647`

![image](https://github.com/Bouni/python-luxtronik/assets/4777401/17cd4672-f705-41bc-8a08-a2df3eefd5b0)

This is in Dutch: Gewenste Ruimtetemperatuur, translating to Desired Room Temperature.
Note, this is different from the "gewenste ruimtetemperatuur" on the first page of the web ui

The value itself is a bit weird (showing the max int), but maybe others have this value set to something else and can confirm these findings.

**Comment by RobinFlikkema** [comment]
> I don't have calc 267. My max is calc 262. I have a Novelan LAD7 with newest Firmware [V2.88.3-9717](https://www.heatpump24.com/software/fetchSoftware.php?softwareID=1)

Ah, i didn't specify the version but mine is running 3.89.3

**Comment by Bouni** [comment]
@RobinFlikkema 

I can confirm that I see the same value with V3.89.4

```
Number: 267   Name: Unknown_Calculation_267             Type: Unknown              Value: 2147483647
```

**Comment by RobinFlikkema** [comment]
> @RobinFlikkema
> 
> I can confirm that I see the same value with V3.89.4
> 
> ```
> Number: 267   Name: Unknown_Calculation_267             Type: Unknown              Value: 2147483647
> ```
> 
> But the value seems strange to me!? Is that if no value is set or somethig like that?

Yeah, however this is also showing in the webinterface. Furthermore, this is the max 32-bit integer. Maybe this only works if you have a specific setup? with Alpha Home for example?

Nonetheless, we at least know that these two values (the one in the calculation_267 and in the webinterface) are the same.

**Comment by Bouni** [comment]
@RobinFlikkema Still we don't kno wwhat the value means. To me this seem like a bug that this value shows up in the webinterface.
I would expect a normal value for desired room temperature like 20.5°C and not a bazillion °C 😂
Maybe it disappears with the next release when they realize that it only should sho up when it has a plausible value or so ...
