### ISSUE TITLE
Dev: Drop black in favour of ruff

### ISSUE THREAD

**Issue by Bouni** [Bouni/python-luxtronik#148]
We should drop **black** as our formatter in favour of **ruff** and in the same take drop **pylint** and fully move towards **ruff**.
Just one dependency and way faster.

**Comment by gerw** [comment]
Just one question from my side: How can I call `ruff` locally in order to be sure that I do not get complains in a pull request? When I do just `ruff format --check`, I get the following on the clean repo:
```
> ruff format --check
Would reformat: luxtronik/__init__.py
Would reformat: luxtronik/discover.py
Would reformat: luxtronik/parameters.py
Would reformat: luxtronik/scripts/dump_changes.py
Would reformat: luxtronik/scripts/dump_luxtronik.py
5 files would be reformatted, 12 files already formatted
```

(Or is `ruff format` currently not used for checking pull requests?)
