### ISSUE TITLE
Datatypes test fails

### ISSUE THREAD

**Issue by Bouni** [Bouni/python-luxtronik#150]
After merging #142 the datatypes test fails:

https://github.com/Bouni/python-luxtronik/actions/runs/7784910695/job/21226348609#step:5:38

@gerw could you take a closer look why?

**Comment by gerw** [comment]
I think because `-100 / 13 = -7.7...` and thus, `int()` and `round()` behave differently.

Do you know why this test didn't fail before?

**Comment by Bouni** [comment]
I hav not sthe slightest idea why the tests didn't fail 🤷🏽‍♂️
