### ISSUE TITLE
Types identified for Parameters 695 and 696

### ISSUE THREAD

**Issue by Duke194** [Bouni/python-luxtronik#174]
Hey I identified some types of parameters.

695: Unknown("ID_Ba_Hz_MK1_akt"), ---> 695: MixedCircuitMode("ID_Ba_Hz_MK1_akt"),
696: Unknown("ID_Ba_Hz_MK2_akt"), ---> 696: MixedCircuitMode("ID_Ba_Hz_MK2_akt"),

Maybe someone can integrate that, would be very kind :)

**Comment by gerw** [comment]
Included in #175.
