### ISSUE TITLE
Error "attribute 'unit'"

### ISSUE THREAD

**Issue by riPlus** [Bouni/python-luxtronik#23]
Hi 

Thank you for this module
I tried to get a calculation and the unit of it.

I get the value, but I get a error when i try to get the unit as described in your doku (readme.md).

```
t_forerun = l.calculations.get(10)
print(t_forerun)
print(t_forerun.unit)
```

Output:
AttributeError: 'Celsius' object has no attribute 'unit'

How can i retrieve the unit?

Thanks and regards
Rico

**Comment by Bouni** [comment]
You can't get the unit, just the type of measurement, in your case for forerun, which is a Celcius value, you can use `t_forerun.measurement_type` to get `'celsius'`.

https://github.com/Bouni/python-luxtronik/blob/master/luxtronik/datatypes.py#L56
