### ISSUE TITLE
measurement_type is used inconsistently

### ISSUE THREAD

**Issue by kbabioch** [Bouni/python-luxtronik#57]
It seems like the `measurement_type` is used inconsistently throughout all of the different datatypes. In some cases it is used to describe the type of data (e.g. `boolean`), in some cases as unit (`celsius`) and in some other cases as abbreviation of the unit (`Hz`).

For instance here it is used as unit (`celsius` written out fully):

https://github.com/Bouni/python-luxtronik/blob/fec29e97a3c0bfd5453bc5af69854d1a6a716009/luxtronik/datatypes.py#L53-L56

In case of `Frequency` it is used as unit (`Hz`, which is an abbreviation for `Hertz`):

https://github.com/Bouni/python-luxtronik/blob/fec29e97a3c0bfd5453bc5af69854d1a6a716009/luxtronik/datatypes.py#L77-L80

In case of other datatypes, it more used as a generic description of the type of data that is being represented, e.g. `boolean`:

I would suggest to make this more consistent by doing the following, also having [Home Assistant's sensor entities](https://developers.home-assistant.io/docs/core/entity/sensor/) in mind.

- Rename `measurement_type` attribute into `type` or `data_type` (since its not always a measurement)
- Introduce a new attribute (`unit`) to describe the unit of the measurement (e.g. `Hertz`, `Watt`, `Kelvin, `Celsius`, etc.).
- Another attribute that contains a visible representation of the `unit`, e.g. `Hz`, `W`, `K`, `°C`). Not super essential, but at least it would be great for the `__repr__` method.
- (Alternatively there could be some kind of class for units that contains the information about the name and abbreviation / visible representation, but that adds additional complexity that is not needed at this point).

Does this make sense? Am I missing something else?

**Comment by Bouni** [comment]
This makes total sense! 

Do you see a chance to kind of auto match HA SensorDeviceClass and Unit in the integration if we act foresighted?

**Comment by kbabioch** [comment]
> Do you see a chance to kind of auto match HA SensorDeviceClass and Unit in the integration if we act foresighted?

Yes, that is what I had in mind here. We could use the `type` to represent / map to [HomeAssistant's Sensor device classes](https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes).

The only problem that I see is that we're currently mixing sensor values (e.g. things that you measure like the temperature) together with some logical values (e.g. boolean), which are `BinarySensors` in Home Assistant.

Probably it should be easy to map within the Home Assistant integration, when we stay consistent and close to the Home Assistant values in our code here.

**Comment by kbabioch** [comment]
So, any further additions / suggestions / improvements? Otherwise this might be worked on once #54 is merged.

**Comment by Bouni** [comment]
I approved #54 a few minutes ago, so you're good to go with this one!

**Comment by kbabioch** [comment]
While #49 has been closed, it probably contains the best summary / data representation so far, including the changes proposed here:

https://github.com/Bouni/python-luxtronik/issues/49#issuecomment-1385508468
