### ISSUE TITLE
Celsius vs. Kelvin datatypes convert differently

### ISSUE THREAD

**Issue by kbabioch** [Bouni/python-luxtronik#58]
The datatypes `Kelvin` and `Celsius` seem to be implemented quite similar, yet a little bit different:

https://github.com/Bouni/python-luxtronik/blob/d9f0e12bb02400ed9d1d0f8f77f3bb426185f78e/luxtronik/datatypes.py#L53-L62

https://github.com/Bouni/python-luxtronik/blob/d9f0e12bb02400ed9d1d0f8f77f3bb426185f78e/luxtronik/datatypes.py#L134-L143

As you can see in case of `Celsius` the value in `to_heatpump` is first cast into a `float` before being multiplied and then converted back into an `int`.

In case of `Kelvin` there is no explicit cast into `float`.

Not sure if it makes a difference in reality (can't think of such a case right now), but also not sure if this is wanted or just overlooked.

Should this be changed?

**Comment by Bouni** [comment]
To be honest, I don't remember why they are not consistent but most likely `int(float(value) * 10) ` would just work fine for `Kelvin`
