### ISSUE TITLE
Wrong data type Circulation_Pump, ID_WEB_HZIO_PWM

### ISSUE THREAD

**Issue by Volti-Ba** [Bouni/python-luxtronik#6]
241: Percent("Circulation_Pump") is a Percent value (circulation pump, no conversion needed) but has an division by 10.
https://github.com/Bouni/luxtronik/blob/master/luxtronik/calculations.py#L244

 183: Percent("ID_WEB_HZIO_PWM"),s a Percent value (circulation pump, no conversion needed) but has an division by 10.
https://github.com/Bouni/luxtronik/blob/master/luxtronik/calculations.py#L186

**Comment by Bouni** [comment]
Shit, I hoped that AIT is at least a little bit consistent in their use of units. So they have Percent values without divider and some with :man_facepalming: 
Will fix that soon ...

**Comment by extin** [comment]
Also, atleast on MSW2-6S, pump that is shown on internal datapage is 173: Bool("ID_WEB_Durchfluss_WQ"), which has Bool as datatype instead of Flow.
https://github.com/Bouni/luxtronik/blob/5f7a206876020b361001da9678f89ff4922da23d/luxtronik/calculations.py#L177

**Comment by Bouni** [comment]
@Volti-Ba Finally found some spare time to fix this. Maybe not the nicest way to introduce a Percent2 class but I think thats what it needs to overcome AITs pile of s***

**Comment by Volti-Ba** [comment]
This need´s also Percent2  ;-.))

241: Percent("Circulation_Pump") is a Percent value (circulation pump, no conversion needed) but has an division by 10.
https://github.com/Bouni/luxtronik/blob/master/luxtronik/calculations.py#L244
