### ISSUE TITLE
Support multiple object instances

### ISSUE THREAD

**Issue by Guzz-T** [Bouni/python-luxtronik#85]
The current implementation uses class variables for the fields `Parameters.parameters`, `Calculations.calculations` and `Visibilities.visibilities`. Due to this, the memory for storing the read data is shared by all instances of the `class Luxtronik`.

#### Possible solution1:
Do not buffer the read data, but return them by calling `read()`. Just define the data structure within the `Calculations.py` (and so on).

#### Possible solution2:
Move the variable declaration into the `__init__()` section of the `class Calculation` (and so on).

#### Benefits:
If the instances are independent from each other, the interface could be used for multiple heat pumps in a multi-threaded application (like `Homeassistant`).

In terms of the OOP, solution 1 would fit better, since the data read does not belong to the luxtronik-read/write-interface

**Comment by Bouni** [comment]
Interested in submitting a PR? I have very limited time at the moment 😓

**Comment by Guzz-T** [comment]
I could give it a try.

**Comment by Guzz-T** [comment]
Got a first draft. Could you give me the rights to push a branch?

**Comment by Guzz-T** [comment]
Opened a pull-request. See: https://github.com/Bouni/python-luxtronik/pull/86
